### PR TITLE
add IndexTree test

### PR DESCRIPTION
**Pull request by Irene315**
Thanks

### CODE REVIEW

**Comment by marklemay** [comment]
Nice! But we probably shouldn't assume any order on pairs

**Comment by Irene315** [comment]
I have tried to make insertion more random.

**Comment by marklemay** [comment]
oh the insertion was fine (except that the hw was harder then we though).  test_pairs does a direct equality test of the list, if someone outputs the test in a different order the test will fail even if it has the correct elements.

**Comment by Irene315** [comment]
Fixed that with importing Data.List

**Comment by marklemay** [comment]
Nice!

**Pull request merged**
